// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgpzeotwrjicbhncvynn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhncHplb3R3cmppY2JobmN2eW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTgyOTAsImV4cCI6MjA3NzEzNDI5MH0.o0AE6ThbVrg1oK67ad1saf_pheNWuxtm_ogMnGRjc1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});